# Background and foreground
background #1c262c
foreground #d6c6c6

# Normal colors
color0 #1c262c
color1 #f6a6aa
color2 #f2d7d8
color3 #ffb347
color4 #f8c8cc
color5 #f2d7d8
color6 #ffb347
color7 #d6c6c6

# Bright colors
color8 #f6a6aa
color9 #f6a6aa
color10 #f2d7d8
color11 #ffb347
color12 #f8c8cc
color13 #f2d7d8
color14 #ffb347
color15 #d6c6c6

cursor_shape     block
# Makes URLs pink when hovering
url_color        #f6a6aa 
copy_on_select   yes
window_padding_width 10

font_family      Courier Prime
bold_font        auto
italic_font      auto
font_size        11.0

# Transparency (0.0 is fully invisible, 1.0 is opaque)
background_opacity 0.82

# Optional: Background blur (Requires picom with kawase blur)
# Since you're using xrender, this might not work yet, 
# but it keeps the text readable!
background_blur 1

# Use Symbols Nerd Font for icons (keeps Courier Prime for text)
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+E0A0-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F372,U+F400-U+F532,U+F0001-U+F1AF0 Symbols Nerd Font Mono
