# --- Background and Foreground ---
background            #1c262c
foreground            #d6c6c6

# --- Terminal Colors (Soft Pastel Palette) ---

# Black
color0                #1c262c
color8                #4b525d

# Red
color1                #f6a6aa
color9                #f6a6aa

# Green
color2                #a3be8c
color10               #b1d196

# Yellow
color3                #ffb347
color11               #fabd2f

# Blue
color4                #81a1c1
color12               #88c0d0

# Magenta (The Sheep Color)
color5                #f2d7d8
color13               #f8c8cc

# Cyan
color6                #8ec07c
color14               #a89984

# White
color7                #d6c6c6
color15               #ffffff

# --- Interactive Elements ---
cursor_shape          block
url_color             #f6a6aa 
copy_on_select        yes
window_padding_width  10

# --- Typography ---
font_family           Courier Prime
bold_font             auto
italic_font           auto
font_size             11.0

# --- Transparency & Blur ---
background_opacity    0.82
background_blur       1

# --- Symbols Nerd Font Mapping ---
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+E0A0-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F372,U+F400-U+F532,U+F0001-U+F1AF0 Symbols Nerd Font Mono